Pi\RsrBundle\Entity\Conseil:
    type: entity
    table: conseils
    id:
        idConseil:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_conseil
            generator:
                strategy: IDENTITY
    fields:
        contenu:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
