Pi\RsrBundle\Entity\Notification:
    type: entity
    table: notification
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cont:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
