home_publications:
    path: /home
    defaults: { _controller: AppBundle:Publication:new }

suppr:
    path:     /{r}/Supprime
    defaults: { _controller: AppBundle:Home:suppr }

grapheChart:
    path: /chart
    defaults: { _controller: AppBundle:Admin:chartLine }